### ISSUE TITLE
Intersected realizations in different scenarios

### ISSUE THREAD

**Issue by XiangLiu-github** [TaufiqHassan/acccmip6#3]
Hi

Thanks for this package! I am wondering can I download two scenarios results with intersected realizations?

For example, I want the BCC-ESM1 model results in historical and SSP585 at the same realizations but skiping other realizations.

Thanks.

**Comment by TaufiqHassan** [comment]
Hi,

Sorry for getting back to you so late! I am glad that you brought up this topic since I was thinking of something similar. I added `-cr` option now in version 5.1.3, which allows to access the common realizations within several experiments. For instance:

historical, ssp245 and ssp245-GHG experiments (for `CanESM5` model and `pr` variable) have a different number of realizations (~40, 25, and 10 respectively). You can select the common realizations among these experiments using `-cr` option as such-

``acccmip6 -o S  -e historical,ssp245,ssp245-GHG -v pr -m CanESM5 -f mon -cr``

Best regards
Taufiq

**Comment by XiangLiu-github** [comment]
Thanks for this, which is very helpful!
