### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'pr_Amon_CNRM-ESM2-1_ssp585_r1i1p1f2_gr_201501-210012.nc

### ISSUE THREAD

**Issue by Jackli9218** [TaufiqHassan/acccmip6#7]
![image](https://user-images.githubusercontent.com/35824720/161472386-42e5a83d-e10d-404e-a813-aba8c5bc0cea.png)

**Comment by Jackli9218** [comment]
Hi everyone,
This error occurred when I downloaded the ssp585 data, but the ssp245 data succeeded.

![image](https://user-images.githubusercontent.com/35824720/161473173-ea496271-6bfe-436f-bdb2-8bbb9bb6ed92.png)

**Comment by TaufiqHassan** [comment]
Hi Jack,

This is a timeout error as you can see in the first part of the error (connection times out). This probably happens if the server is busy and self resolvable. So, if this happens, you can try it at a later time, and hopefully, the server-side issue is resolved by then. It is currently  working for me:  

 acccmip6 -o D -m CNRM-ESM2-1 -e ssp585 -v pr -f mon -yr 10 -rlzn 1 -skip 1p2

Finding server . . .

pr_Amon_CNRM-ESM2-1_ssp585_r1i1p1f2_gr_201501-210012.nc is available!

Downloading  2% |█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░| 2/100MB 0.54 MB/s

Taufiq

**Comment by Jackli9218** [comment]
Hi Taufiq,

Thank you very much for your reply and help!

Your solution worked for me!

![image](https://user-images.githubusercontent.com/35824720/161661471-5d1aa624-0af3-483e-9356-54f974e9c0da.png)

Thank you again and your work for this acccmip6 package!

Jack
